# Generated by Django 2.1.5 on 2020-03-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_post_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slider',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
