# Generated by Django 3.0 on 2020-04-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_team_teamview'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='categories',
            field=models.ManyToManyField(to='src.Category'),
        ),
    ]
